---
- name: Template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx container

- name: Restart nginx container
  command: podman restart nginx-proxy
  ignore_errors: true